# Generated by Django 5.2.2 on 2025-06-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet_identidad', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('carrera', models.CharField(max_length=50)),
                ('ano', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(max_length=50, unique=True)),
                ('numero_ip', models.GenericIPAddressField(unique=True)),
                ('tiene_internet', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='AccesoFueraClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('PROY', 'Proyecto'), ('TRAB', 'Trabajo extra clase'), ('OTRO', 'Otro')], max_length=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.estudiante')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.maquina')),
            ],
            options={
                'verbose_name_plural': 'Accesos Fuera de Clase',
            },
        ),
        migrations.CreateModel(
            name='AccesoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.CharField(max_length=100)),
                ('tipo_clase', models.CharField(choices=[('LAB', 'Laboratorio'), ('SEM', 'Seminario'), ('EP', 'Evaluación parcial'), ('EF', 'Evaluación final')], max_length=3)),
                ('profesor', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.estudiante')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.maquina')),
            ],
            options={
                'verbose_name_plural': 'Accesos en Clase',
            },
        ),
    ]
